{{- if not .Values.slackWebhookUrlSecretKeyRef -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-pod-restart-info-collector.fullname" . }}
  labels:
    {{- include "k8s-pod-restart-info-collector.labels" . | nindent 4 }}
type: Opaque
data:
  MICROSOFT_TEAMS_WEBHOOK_URL: {{ required "MICROSOFT_TEAMS_WEBHOOK_URL is required" .Values.MICROSOFT_TEAMS_WEBHOOK_URL | b64enc | quote }}
{{- end -}}
